require("packer-config").setup()
require("options")
require("keymap-config")
require("lualine-config")
require("barbar-config")
require("nvim-tree-config")
require("toggleterm-config")
require("comment-nvim-config")
require("colorizer-config")
require("indent-blankline-config")
require("telescope-config")
require("treesitter-config")
require("mason-config")
require("lsp-config.lsp")
require("lsp-config.completion")
require("lsp-config.null-ls")

-- -- Global mappings.
-- -- See `:help vim.diagnostic.*` for documentation on any of the below functions
-- vim.keymap.set('n', '<space>e', vim.diagnostic.open_float)
-- vim.keymap.set('n', '[d', vim.diagnostic.goto_prev)
-- vim.keymap.set('n', ']d', vim.diagnostic.goto_next)
-- vim.keymap.set('n', '<space>q', vim.diagnostic.setloclist)
