require("packer-config").setup()
require("kanagawa-config")
require("options")
require("keymap-config")
require("lualine-config")
require("barbar-config")
require("gitsigns-config")
require("nvim-tree-config")
require("toggleterm-config")
require("comment-nvim-config")
require("colorizer-config")
require("indent-blankline-config")
require("telescope-config")
require("treesitter-config")
require("mason-config")
require("lsp-config.lsp")
require("lsp-config.completion")
require("lsp-config.null-ls")

vim.filetype.add({ filename = { ["BUILD"] = "python" } })
